services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cinemabot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 3s
      retries: 5

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
